# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-27 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alipay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DutCustomerAgreementSign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agreement_no', models.CharField(blank=True, max_length=20, null=True)),
                ('sign_time', models.DateTimeField(auto_now_add=True)),
                ('sign_modify_time', models.DateTimeField(auto_now=True)),
                ('valid_time', models.DateTimeField(auto_now_add=True)),
                ('invalid_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('external_sign_no', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('TEMP', 'TEMP'), ('NORMAL', 'NORMAL'), ('STOP', 'STOP')], default='NORMAL', max_length=6)),
                ('alipay_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='alipay.AlipayUser')),
            ],
        ),
    ]
