# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay_proxy', '0002_auto_20171227_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutcustomeragreementsign',
            name='external_sign_no',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
