# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-15 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay_proxy', '0003_dutcustomeragreementsign_external_sign_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='dutcustomeragreementsign',
            name='agreement_detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
