# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 03:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaycontext',
            name='partner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='alipay.AlipayUser'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='alipaycontext',
            name='trans_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
