# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0002_auto_20171228_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='alipaycontext',
            name='trade_no',
            field=models.TextField(blank=True, max_length=64, null=True),
        ),
    ]
