# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 03:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0003_alipaycontext_trade_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipaycontext',
            name='context',
            field=models.TextField(blank=True, null=True),
        ),
    ]
