# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 06:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0004_auto_20171228_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alipaycontext',
            old_name='trans_time',
            new_name='trade_time',
        ),
    ]
