# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-28 06:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0005_auto_20171228_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alipayuser',
            name='user_id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
