# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alipay', '0007_alipayuser_pay_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alipayuser',
            old_name='pay_result',
            new_name='is_success',
        ),
        migrations.AddField(
            model_name='alipayuser',
            name='other_options',
            field=models.TextField(blank=True, null=True),
        ),
    ]
